"""empty message

Revision ID: 5a58cfe5e193
Revises: 583092e42e25
Create Date: 2022-11-25 07:43:47.547715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a58cfe5e193'
down_revision = '583092e42e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_roles', sa.String(length=650), nullable=True))
    op.drop_column('users', 'skill_metrix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skill_metrix', sa.VARCHAR(length=650), nullable=True))
    op.drop_column('users', 'user_roles')
    # ### end Alembic commands ###
