"""empty message

Revision ID: 949500dd8659
Revises: eaf16656d1ae
Create Date: 2022-08-12 10:57:08.659702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949500dd8659'
down_revision = 'eaf16656d1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_scrap',
    sa.Column('mlid', sa.Integer(), nullable=False),
    sa.Column('scrap', sa.String(length=650), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('scrap_type', sa.String(length=50), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mlid')
    )
    op.create_table('process_params',
    sa.Column('ppid', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('technology', sa.String(length=50), nullable=True),
    sa.Column('parameters', sa.String(length=6550), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ppid')
    )
    op.create_table('production',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('prodate', sa.Date(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('mcode', sa.String(length=6), nullable=True),
    sa.Column('product_params', sa.String(length=655), nullable=True),
    sa.Column('line', sa.String(length=50), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('reliability', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('msu', sa.Integer(), nullable=True),
    sa.Column('skedule_time', sa.BigInteger(), nullable=True),
    sa.Column('downtime', sa.BigInteger(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('upst', sa.Integer(), nullable=True),
    sa.Column('updt', sa.BigInteger(), nullable=True),
    sa.Column('major_loss', sa.String(length=655), nullable=True),
    sa.Column('scrap', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('cases', sa.String(length=655), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('skus',
    sa.Column('skuid', sa.Integer(), nullable=False),
    sa.Column('productcode', sa.String(length=50), nullable=True),
    sa.Column('gcas', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('skuid')
    )
    op.add_column('equipment', sa.Column('product_params', sa.String(length=6500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'product_params')
    op.drop_table('skus')
    op.drop_table('production')
    op.drop_table('process_params')
    op.drop_table('material_scrap')
    # ### end Alembic commands ###
