"""empty message

Revision ID: c00076206c14
Revises: 1e75a0bbc7f6
Create Date: 2022-09-14 01:36:46.235717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00076206c14'
down_revision = '1e75a0bbc7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('pass_mark', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('priority', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'priority')
    op.drop_column('trainings', 'pass_mark')
    # ### end Alembic commands ###
