"""empty message

Revision ID: eaf16656d1ae
Revises: 5844f9522dc6
Create Date: 2022-08-07 07:56:54.318107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf16656d1ae'
down_revision = '5844f9522dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_password')
    # ### end Alembic commands ###
