"""empty message

Revision ID: f238038b1eab
Revises: 58e4a9c65790
Create Date: 2022-11-17 15:38:13.357008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f238038b1eab'
down_revision = '58e4a9c65790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('rname', sa.String(length=120), nullable=False),
    sa.Column('trainings', sa.String(length=6550), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    # ### end Alembic commands ###
