"""empty message

Revision ID: 0a9397faa000
Revises: 4443032730e9
Create Date: 2022-07-22 21:54:22.027652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9397faa000'
down_revision = '4443032730e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_auditlog',
    sa.Column('useraction_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('adminuser', sa.String(length=50), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.Column('narration', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('useraction_id')
    )
    op.create_table('alogin',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('usertype', sa.String(length=30), nullable=False),
    sa.Column('loginTime', sa.String(length=50), nullable=False),
    sa.Column('loginDate', sa.String(length=50), nullable=False),
    sa.Column('lcount', sa.BigInteger(), nullable=False),
    sa.Column('loginkey', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('login_id')
    )
    op.create_table('asessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_time', sa.String(length=45), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('session_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('abbr', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('hod', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('failed_logins',
    sa.Column('failedid', sa.BigInteger(), nullable=False),
    sa.Column('usertype', sa.String(length=30), nullable=False),
    sa.Column('logon_email', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=30), nullable=False),
    sa.Column('is_real_user', sa.Integer(), nullable=False),
    sa.Column('regtime', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('failedid')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('acctype', sa.Enum('user', 'admin'), nullable=True),
    sa.Column('fname', sa.String(length=45), nullable=False),
    sa.Column('sname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('adminlevel', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.Integer(), nullable=False),
    sa.Column('block_stat', sa.Integer(), nullable=False),
    sa.Column('passresetcode', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_password_reset', sa.String(length=50), nullable=True),
    sa.Column('activated', sa.Integer(), nullable=True),
    sa.Column('activatecode', sa.String(length=255), nullable=True),
    sa.Column('last_activation_code_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('failed_logins')
    op.drop_table('departments')
    op.drop_table('asessions')
    op.drop_table('alogin')
    op.drop_table('admin_auditlog')
    # ### end Alembic commands ###
