"""empty message

Revision ID: 132304a91ff6
Revises: 32b48fe078c2
Create Date: 2023-08-15 22:02:40.009916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132304a91ff6'
down_revision = '32b48fe078c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_qualifications', sa.Column('certificate_link', sa.String(length=650), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_qualifications', 'certificate_link')
    # ### end Alembic commands ###
