"""empty message

Revision ID: 19e8eddba358
Revises: 4b541097b1dc
Create Date: 2023-01-12 21:37:54.332158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e8eddba358'
down_revision = '4b541097b1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'team')
    # ### end Alembic commands ###
