"""empty message

Revision ID: 1e75a0bbc7f6
Revises: 1ebf333239c2
Create Date: 2022-09-12 18:24:21.365165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e75a0bbc7f6'
down_revision = '1ebf333239c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_qualifications',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('q_date', sa.DateTime(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'REPEAT'), nullable=False),
    sa.PrimaryKeyConstraint('qid')
    )
    op.create_table('trainings',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('quiz_link', sa.String(length=650), nullable=True),
    sa.Column('suc_link', sa.String(length=650), nullable=True),
    sa.Column('doc_link', sa.String(length=650), nullable=True),
    sa.Column('extra_resource', sa.String(length=650), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    op.drop_table('my_qualifications')
    # ### end Alembic commands ###
