"""empty message

Revision ID: 1ebf333239c2
Revises: 42ac3c4f8641
Create Date: 2022-08-31 16:44:06.101316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebf333239c2'
down_revision = '42ac3c4f8641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('start_tyme', sa.DateTime(), nullable=True))
    op.add_column('production', sa.Column('end_tyme', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'end_tyme')
    op.drop_column('production', 'start_tyme')
    # ### end Alembic commands ###
