"""empty message

Revision ID: 32b48fe078c2
Revises: bb058be875a5
Create Date: 2023-07-28 07:54:54.042442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b48fe078c2'
down_revision = 'bb058be875a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_qualifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualifier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logged_by', sa.Integer(), nullable=True))
        batch_op.alter_column('q_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_qualifications', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('q_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('logged_by')
        batch_op.drop_column('qualifier')

    # ### end Alembic commands ###
