"""empty message

Revision ID: 42ac3c4f8641
Revises: 9b0bd8a87782
Create Date: 2022-08-30 07:51:37.080767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ac3c4f8641'
down_revision = '9b0bd8a87782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('volume', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('production', sa.Column('exp_volume', sa.Numeric(precision=18, scale=2), nullable=True))
    op.drop_column('production', 'exp_msu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('exp_msu', sa.NUMERIC(precision=18, scale=2), nullable=True))
    op.drop_column('production', 'exp_volume')
    op.drop_column('production', 'volume')
    # ### end Alembic commands ###
