"""empty message

Revision ID: 4443032730e9
Revises: cc4a5483b189
Create Date: 2022-05-13 05:35:52.403814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4443032730e9'
down_revision = 'cc4a5483b189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reason_four', sa.Column('end_tag', sa.Integer(), nullable=True))
    op.add_column('reason_three', sa.Column('end_tag', sa.Integer(), nullable=True))
    op.add_column('reason_two', sa.Column('end_tag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reason_two', 'end_tag')
    op.drop_column('reason_three', 'end_tag')
    op.drop_column('reason_four', 'end_tag')
    # ### end Alembic commands ###
