"""empty message

Revision ID: 4b541097b1dc
Revises: e04d3e14feeb
Create Date: 2023-01-08 00:16:55.297700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b541097b1dc'
down_revision = 'e04d3e14feeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_qualifications', sa.Column('suc_status', sa.Enum('completed', 'pending', 'na'), default='na'))
    op.add_column('my_qualifications', sa.Column('suc_q_date', sa.DateTime(), nullable=True))
    op.add_column('my_qualifications', sa.Column('percent', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('suc_id', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('suc', sa.Integer(), default=0))
    op.drop_column('trainings', 'suc_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('suc_link', sa.VARCHAR(length=650), nullable=True))
    op.drop_column('trainings', 'suc')
    op.drop_column('trainings', 'suc_id')
    op.drop_column('my_qualifications', 'percent')
    op.drop_column('my_qualifications', 'suc_q_date')
    op.drop_column('my_qualifications', 'suc_status')
    # ### end Alembic commands ###
