"""empty message

Revision ID: 583092e42e25
Revises: f238038b1eab
Create Date: 2022-11-25 07:33:19.145628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583092e42e25'
down_revision = 'f238038b1eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('description', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'description')
    # ### end Alembic commands ###
