"""empty message

Revision ID: 58e4a9c65790
Revises: b4a379bae86c
Create Date: 2022-10-30 16:04:45.874458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e4a9c65790'
down_revision = 'b4a379bae86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('t_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 't_code')
    # ### end Alembic commands ###
