"""empty message

Revision ID: 7d234870af01
Revises: 32b48fe078c2
Create Date: 2023-08-12 15:44:50.388697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d234870af01'
down_revision = '32b48fe078c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_qualifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_link', sa.String(length=650), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_qualifications', schema=None) as batch_op:
        batch_op.drop_column('certificate_link')

    # ### end Alembic commands ###
