"""empty message

Revision ID: 9b0bd8a87782
Revises: ef76f88e97af
Create Date: 2022-08-28 12:22:15.617261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0bd8a87782'
down_revision = 'ef76f88e97af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('msu', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('production', sa.Column('exp_msu', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'exp_msu')
    op.drop_column('production', 'msu')
    # ### end Alembic commands ###
