"""empty message

Revision ID: b4a379bae86c
Revises: c00076206c14
Create Date: 2022-09-14 03:21:44.727649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a379bae86c'
down_revision = 'c00076206c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skill_metrix', sa.String(length=650), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skill_metrix')
    # ### end Alembic commands ###
