"""empty message

Revision ID: b4fb3ef0abb6
Revises: 949500dd8659
Create Date: 2022-08-22 15:00:27.950055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fb3ef0abb6'
down_revision = '949500dd8659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('brand', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'brand')
    # ### end Alembic commands ###
