"""empty message

Revision ID: cc4a5483b189
Revises: 
Create Date: 2022-04-04 21:57:47.579690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4a5483b189'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causes',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=225), nullable=True),
    sa.Column('cause_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cid')
    )
    op.add_column('equipment', sa.Column('m_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'm_code')
    op.drop_table('causes')
    # ### end Alembic commands ###
