"""empty message

Revision ID: e04d3e14feeb
Revises: 5a58cfe5e193
Create Date: 2022-11-25 08:58:00.661063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04d3e14feeb'
down_revision = '5a58cfe5e193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('rnr', sa.String(length=6550), nullable=True))
    op.add_column('user_roles', sa.Column('report_to', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'report_to')
    op.drop_column('user_roles', 'rnr')
    # ### end Alembic commands ###
