"""empty message

Revision ID: ef76f88e97af
Revises: 610bb5309fdc
Create Date: 2022-08-28 12:20:42.067763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef76f88e97af'
down_revision = '610bb5309fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'exp_msu')
    op.drop_column('production', 'msu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('msu', sa.INTEGER(), nullable=True))
    op.add_column('production', sa.Column('exp_msu', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
